import type { Artwork } from "@/space/types";

/** The artwork table — transcribed verbatim from design/gallery3d.js's `C`. */
export const ARTWORKS: Record<string, Artwork> = {
  p1: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-p1.jpg",
    title: "The Silhouette",
    meta: "BLSKY · 20xx",
    ar: 2 / 3,
    note: "Weirdly enough, this shot was taken during our company outing. But at that time, we had a blackout. This scene is definitely an accident that I saw. I immediately took my camera",
  },
  p2: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-1.jpg",
    title: "The Walk",
    meta: "Yoyogi Park, Tokyo · 2024",
    ar: 2 / 3,
    note: "We just finished our walk on Yoyogi Park that day. Onto our next destination! Until I saw this. Two strangers that probably don't know each other, walking in the same direction",
  },
  p3: {
    src: "/art/p3.jpg",
    title: "Hōzenji Yokochō, Rain",
    meta: "Namba, Osaka · 2025",
    ar: 1.5,
    note: "Wet stone holds light better than anything else in the city.",
  },
  x1: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x1.jpg",
    title: "The Apotheosis of Watermelon Mortal",
    meta: "Pasar Induk Kramat Djati, Jakarta · 2023",
    ar: 2 / 3,
    note: "It was a session with BursaKameraProfesional, with a pro photographer leading us. Another scene I manage to capture, when I accidentally realize how interesting these workers pass the watermelon between each other. One of my fav shot I took honestly",
  },
  x2: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x2.jpg",
    title: "",
    meta: "Kyoto · 2026",
    ar: 1,
    note: "I and my mom just arrived in Kyoto that day. So we put our luggage away in the hotel, and had a walk before the check-in time. Spotted this man. Took a shot. I kinda like the result",
  },
  x3: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x3.jpg",
    title: "Rainy Alley",
    meta: "Dotonbori, Osaka · 2026",
    ar: 2 / 3,
    note: "Interesting scene on this alley on Dotonbori. I'm thankful for the one with the light colored jacket. It actually made the scene",
  },
  x7: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x7.jpg",
    title: "The Garden Rhapsody in BW",
    meta: "Gardens by the Bay · 2025",
    ar: 1.5,
    note: "The light show in Gardens by the Bay of Singapore, in Black and White. It is definitely a personal choice on why I took this in black and white",
  },
  x8: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x8.jpg",
    title: "The Early Winter",
    meta: "Odori Park, Sapporo · 2025",
    ar: 1.5,
    note: "I miss Odori Park so much during this early winter. We decided to try Odori Park that day. Our first time in Sapporo honestly. My first snow ever also. The memory behind this picture still lingers in my heart. I want to come back, to Sapporo",
  },
  x9: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x9.jpg",
    title: "The Garden Rhapsody in BW, too",
    meta: "Gardens by the Bay · 2025",
    ar: 1.5,
    note: "The light show in Gardens by the Bay of Singapore in Black and White. Again, the black and white is a personal touch",
  },
  sp1: {
    ph: "SEALED · 2:3",
    title: "Untitled",
    meta: "awaiting print",
    ar: 2 / 3,
    note: "A print reserved for guests holding the right token.",
  },
  x10_1: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x10_1.jpg",
    title: "Yoyogi Rest",
    meta: "Yoyogi Park · 2024",
    ar: 1.5,
    note: "a decent public open public space for everyone. You can just rest there, and enjoy a warm, but a bit cool day",
  },
  x10_2: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x10_2.jpg",
    title: "to Yoyogi Park",
    meta: "Yoyogi Park · 2024",
    ar: 1.5,
    note: "The signage that leads you to other places, as well. I mean, we got to capture this, once in a while, right?",
  },
  x10_3: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x10_3.jpg",
    title: "Yoyogi Serenity",
    meta: "Yoyogi Park · 2024",
    ar: 1.5,
    note: "This picture speaks the necessity for us to have a rather decent public space. Look at the man, enjoying his free time, under the sunlight",
  },
  x10_6: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x10_6.jpg",
    title: "Reminiscing Kimi no na wa",
    meta: "The National Art Center, Tokyo · 2026",
    ar: 2 / 3,
    note: "This is probably one of the few sentimental picture I have taken. Kimi no na wa will forever has a special place in my heart",
  },
  x10_4: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x10_4.jpg",
    title: "Yoyogi Serenity too",
    meta: "Yoyogi Park · 2024",
    ar: 1.5,
    note: "a windy day at Yoyogi Park. This scene is rather, interesting to me. Two obaa-chan just casually enjoying their time here, talking",
  },
  x10_5: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x5.jpg",
    title: "The Park, the Man, and...",
    meta: "Osaka Castle Park, Osaka · 2026",
    ar: 1.5,
    note: "The serene scenery of a man, reading, accompanied by his faithful city bike. I immediately stole this scene, from a far. I think I did not present it well, but, when I saw this scene that day, it felt like a painting",
  },

  x11_1: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x11_1.jpg",
    // ph: "11_1",
    title: "The Statue of Many",
    meta: "Kamakura · 2026",
    ar: 1.5,
    note: "I just feel like capturing it when I saw the statues are kind of, well expose to the light. Fun fact: I made this as my phone lock screen",
  },
  x11_2: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x11_2.jpg",
    // ph: "11_2",
    title: "Capturing..",
    meta: "Tokyo Station, Tokyo · 2024",
    ar: 1.5,
    note: "The moment when capturing the scene of Tokyo Station. I like how my friend and the man behind him that facing the other way looks okay in this composition.",
  },
  x11_3: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall_x11_3.jpg",
    // ph: "11_3",
    title: "Framing the Passing Plane",
    meta: "Shibuya, Tokyo · 2026",
    ar: 1.5,
    note: "I was getting myself and my mom to Gu that day in Shibuya. When we walked the road that day, I saw planes a couple of times, passed by. Hence, the photo",
  },
  x11_4: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall_x11_4.jpg",
    // ph: "11_4",
    title: "The Man, under the Rain",
    meta: "Uji · 2024",
    ar: 1.5,
    note: "I remembered that we were waiting for a bus that day. We just visited Nara a few hours earlier. Uji was raining that day. A memorable walk indeed, before I met the man with this umbrella.",
  },
  
  x6: {
    // ph: "PHOTO 09 · 2:3",
    src: 'https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/east_x6.jpg',
    title: "The Airport",
    meta: "I Gusti Ngurah Rai Airport, Badung · 2022",
    ar: 2 / 3,
    note: "Interesting scene (to me. Just me? Okay) that day. Gapura is a rather common structure in Bali, and it is also the same case for I Gusti Ngurah Rai Airport",
  },
  x4: {
    // ph: "PHOTO 07 · 3:2",
    src: 'https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/east_x4.jpg',
    title: "The Station Slow Shutter",
    meta: "Manggarai · 2026",
    ar: 1.5,
    note: "The reason I was going with slow shutter, is so I can lock a quiet moment, like this, in the middle of a very busy, and active place",
  },
  x5: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/east_x5.jpg",
    title: "Get on the Angkot",
    meta: "Lebak Bulus MRT Station, South Jakarta · 2026",
    ar: 1.5,
    note: "Probably one of a few times when I just want to capture pictures, with different angles. I mean, you must have your being bored phase, once in a while, right?",
  },
  e1: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/east_e1.jpg",
    // ph: "e_1",
    title: "The Secrecy of the Youngs",
    meta: "Taman Ismail Marzuki, Central Jakarta · 2026",
    ar: 1.5,
    note: "Oh, so I just got my picture showed in an exhibition by Potopotokota that day, so I stroll around Taman Ismail Marzuki. Capture these gals having whatever their discussion under that spot light. Gotta capture it, right? Maybe they plan something, beautiful?",
  },
  e2: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/east_e2.jpg",
    // ph: "e_2",
    title: "Man, at the Top",
    meta: "Taman Ismail Marzuki, Central Jakarta · 2026",
    ar: 1.5,
    note: "Still on the Taman Ismail Marzuki that day. Weird how I just got back from toilet, when somehow, I spot this scene (well, my friend did first honestly). There, I took it",
  },
  e3: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/east_e3.jpg",
    // ph: "e_3",
    title: "Clocking Clock Clock Clock. Tik Tak, Tik Tak, Tik Tak",
    meta: "Asakusa · 2026",
    ar: 1,
    note: "I and my mom had a small walk in the morning, near Asakusa. No other reason than being interested when I took this one",
  },
  e4: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/east_e4.jpg",
    // ph: "e_4",
    title: "The Building",
    meta: "Asakusa · 2026",
    ar: 1,
    note: "Still during the morning walk in Asakusa",
  },
  e5: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/east_e5.jpg",
    // ph: "e_5",
    title: "Osaka Castle, Park",
    meta: "Osaka Castle Park, Osaka · 2026",
    ar: 2 / 3,
    note: "So, what I just knew is that, it's actually super fun going around the Osaka Castle Park. I can't stress this enough how we, Indonesian need more open public space. I can feel the air, the sunlight, the people, from this photo alone",
  },
  e6: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/east_e6.jpg",
    // ph: "e_6",
    title: "The Early Winter, for the Tropical",
    meta: "Sapporo · 2024",
    ar: 1.5,
    note: "Our first time in Sapporo, is amazing. I mean, that's our first 3 degree Celcius, with snows all over us! I miss this scene. I miss this a lot",
  },
  e7: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/east_e7.jpg",
    // ph: "e_7",
    title: "The Sapporo Nite, The Song, and the Cutie Little Doggie",
    meta: "Sapporo · 2024",
    ar: 2/3,
    note: "Our second night stroll in Sapporo. It's staggeringly cold, for us! Just 3 dudes, enjoying a night in Sapporo",
  },

  n1: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/north_n1.jpg",
    // ph: "n_1",
    title: "[N] The Lone, TREE",
    meta: "- · 20xx",
    ar: 1.5,
    note: "[N] I still have the same feeling, when I first captured this that day with my Canon EOS 700D, and today, when I look at this photo. I can feel the loneliness in here. And I'm making sure (trying) that the feeling is delivered to you, the viewers",
  },
  n2: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/north_n2.jpg",
    // ph: "n_2",
    title: "[N] MALIQ & D'ESSENTIALS",
    meta: "Institut Teknologi Sepuluh Nopember · 20xx",
    ar: 1.5,
    note: "[N] This is the first time that I'm so grateful for having a tele lens. This event's called Tokopedia Campus Gigs. Free event, and somehow, maybe because I was a student there, the security let me to use my tele there. One of my very sentimental photo",
  },
  n3: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/north_n3.jpg",
    // ph: "n_3",
    title: "[N] Lunar",
    meta: "- · 20xx",
    ar: 1.5,
    note: "[N] Another grateful moment, for having a tele lens. Not my first attempt on lunar shot, but also I'm grateful for every lunar shot I made, since the first time of having one",
  },
  n4: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/north_n4.jpg",
    // ph: "n_4",
    title: "[N] GAES on a Vacay",
    meta: "- · 20xx",
    ar: 2/3,
    note: "[N] My college years. Still using that bad boi EOS 700D. I mean, it's a cool pose, good silhouette. So, why not?",
  },
  n5: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/north_n5.jpg",
    // ph: "n_5",
    title: "The Walk, The Fushimi Inari",
    meta: "Fushimi Inari, Kyoto · 2026",
    ar: 2/3,
    note: "The torii gates are endless in Fushimi Inari. You have seen it a lot on the internet. So, here you go. Another photos in Fushimi Inari. But maybe (and I hope so), it's a bit different than the rest",
  },
  n6: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/north_n6.JPG",
    // ph: "n_6",
    title: "Holding on",
    meta: "Singapore · 2025",
    ar: 1.5,
    note: "There was a lightshow in Singapore that day. Can't even remember why I went to Singapore that day. But, a friend decided to accompanied me that day. This was in one of the light play that day. But I guess, I took a picture of something else, right?",
  },
  n7: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/north_n7.jpg",
    // ph: "n_7",
    title: "Takeshita Street Magic, in the Pouring Rain",
    meta: "Takeshita Street, Tokyo · 2026",
    ar: 2/3,
    note: "Takeshita Street. The destination that day was actually a Mofusand Store. But, somehow, I manage to pass by Takeshita Street. It was raining that day. Again, one of my fav shot so far",
  },
  n8: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/north_n8.JPG",
    // ph: "n_8",
    title: "Golder Hour Kawasaki",
    meta: "Kawasaki · 2026",
    ar: 2/3,
    note: "I just happened to pass by one of the alley that day, during my stroll in Kawasaki. Technically, I can't remember where, in Kawasaki. So let's stay with that. Another accidental spot from my eyes. I kind of like the flare",
  },
};
