import type { Artwork } from "@/space/types";

/** The artwork table — transcribed verbatim from design/gallery3d.js's `C`. */
export const ARTWORKS: Record<string, Artwork> = {
  p1: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-p1.JPG",
    title: "The Silhouette",
    meta: "BLSKY · 20xx",
    ar: 2 / 3,
    note: "The silhouette of a friend. During a blackout, apparently",
  },
  p2: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-1.jpg",
    title: "The Walk",
    meta: "Yoyogi Park, Tokyo · 2024",
    ar: 2 / 3,
    note: "A rather comfortable walk between two strangers",
  },
  p3: {
    src: "/art/p3.jpg",
    title: "Hōzenji Yokochō, Rain",
    meta: "Namba, Osaka · 2025",
    ar: 1.5,
    note: "Wet stone holds light better than anything else in the city.",
  },
  x1: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x1.JPG",
    title: "The Park, the Man, and...",
    meta: "Osaka Castle Park, Osaka · 2026",
    ar: 1.5,
    note: "The serene scenery of a man, reading, accompanied by his faithful city bike",
  },
  x2: {
    ph: "PHOTO 05 · 4:5",
    title: "Untitled",
    meta: "awaiting print",
    ar: 0.8,
    note: "An empty hang. Drop a photograph in to fill it.",
  },
  x3: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x3.JPG",
    title: "The Apotheosis of Watermelon Mortal",
    meta: "Pasar Induk Kramat Djati, Jakarta · 2023",
    ar: 2 / 3,
    note: "The daily routine of workers in Pasar Induk Kramat Djati",
  },
  x4: {
    ph: "PHOTO 07 · 1:1",
    title: "Untitled",
    meta: "awaiting print",
    ar: 1.0,
    note: "An empty hang. Drop a photograph in to fill it.",
  },
  x5: {
    ph: "PHOTO 08 · 4:5",
    title: "Untitled",
    meta: "awaiting print",
    ar: 0.8,
    note: "An empty hang. Drop a photograph in to fill it.",
  },
  x6: {
    ph: "PHOTO 09 · 3:2",
    title: "Untitled",
    meta: "awaiting print",
    ar: 1.5,
    note: "An empty hang. Drop a photograph in to fill it.",
  },
  x7: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x7.JPG",
    title: "The Garden Rhapsody in BW",
    meta: "Gardens by the Bay · 2025",
    ar: 1.5,
    note: "The light show in Gardens by the Bay of Singapore, in Black and White",
  },
  x8: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x8.JPG",
    title: "The Early Winter",
    meta: "Odori Park, Sapporo · 2025",
    ar: 1.5,
    note: "An empty hang. Drop a photograph in to fill it.",
  },
  x9: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x9.JPG",
    title: "The Garden Rhapsody in BW, too",
    meta: "Gardens by the Bay · 2025",
    ar: 1.5,
    note: "The light show in Gardens by the Bay of Singapore in Black and White",
  },
  sp1: {
    ph: "SEALED · 2:3",
    title: "Untitled",
    meta: "awaiting print",
    ar: 2 / 3,
    note: "A print reserved for guests holding the right token.",
  },
};
