import type { Artwork } from "@/space/types";

/** The artwork table — transcribed verbatim from design/gallery3d.js's `C`. */
export const ARTWORKS: Record<string, Artwork> = {
  p1: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-p1.jpg",
    title: "The Silhouette",
    meta: "BLSKY · 20xx",
    ar: 2 / 3,
    note: "The silhouette of a friend. During a blackout, apparently",
  },
  p2: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-1.jpg",
    title: "The Walk",
    meta: "Yoyogi Park, Tokyo · 2024",
    ar: 2 / 3,
    note: "A rather comfortable walk between two strangers",
  },
  p3: {
    src: "/art/p3.jpg",
    title: "Hōzenji Yokochō, Rain",
    meta: "Namba, Osaka · 2025",
    ar: 1.5,
    note: "Wet stone holds light better than anything else in the city.",
  },
  x1: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x1.jpg",
    title: "The Apotheosis of Watermelon Mortal",
    meta: "Pasar Induk Kramat Djati, Jakarta · 2023",
    ar: 2 / 3,
    note: "The daily routine of workers in Pasar Induk Kramat Djati",
  },
  x2: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x2.jpg",
    title: "",
    meta: "Kyoto · 2026",
    ar: 1,
    note: "A stranger in a familiar crowd",
  },
  x3: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x3.jpg",
    title: "Rainy Alley",
    meta: "Dotonbori, Osaka · 2026",
    ar: 2 / 3,
    note: "Interesting scene on this alley on Dotonbori. I'm thankful for the one with the light colored jacket. It actually made the scene",
  },
  x7: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x7.jpg",
    title: "The Garden Rhapsody in BW",
    meta: "Gardens by the Bay · 2025",
    ar: 1.5,
    note: "The light show in Gardens by the Bay of Singapore, in Black and White",
  },
  x8: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x8.jpg",
    title: "The Early Winter",
    meta: "Odori Park, Sapporo · 2025",
    ar: 1.5,
    note: "An empty hang. Drop a photograph in to fill it.",
  },
  x9: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x9.jpg",
    title: "The Garden Rhapsody in BW, too",
    meta: "Gardens by the Bay · 2025",
    ar: 1.5,
    note: "The light show in Gardens by the Bay of Singapore in Black and White",
  },
  sp1: {
    ph: "SEALED · 2:3",
    title: "Untitled",
    meta: "awaiting print",
    ar: 2 / 3,
    note: "A print reserved for guests holding the right token.",
  },
  x10_1: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x10_1.jpg",
    title: "Yoyogi Rest",
    meta: "Yoyogi Park · 2024",
    ar: 1.5,
    note: "a decent public open public space for everyone. You can just rest there, and enjoy a warm, but a bit cool day",
  },
  x10_2: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x10_2.jpg",
    title: "to Yoyogi Park",
    meta: "Yoyogi Park · 2024",
    ar: 1.5,
    note: "The signage that leads you to other places, as well",
  },
  x10_3: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x10_3.jpg",
    title: "Yoyogi Serenity",
    meta: "Yoyogi Park · 2024",
    ar: 1.5,
    note: "This picture speaks the necessity for us to have a rather decent public space. Look at the man, enjoying his free time, under the sunlight",
  },
  x10_6: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x10_6.jpg",
    title: "Reminiscing Kimi no na wa",
    meta: "The National Art Center, Tokyo · 2026",
    ar: 2 / 3,
    note: "This is probably one of the few sentimental picture I have taken. Kimi no na wa will forever has a special place in my heart",
  },
  x10_4: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x10_4.jpg",
    title: "Yoyogi Serenity too",
    meta: "Yoyogi Park · 2024",
    ar: 1.5,
    note: "a windy day at Yoyogi Park",
  },
  x10_5: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x5.jpg",
    title: "The Park, the Man, and...",
    meta: "Osaka Castle Park, Osaka · 2026",
    ar: 1.5,
    note: "The serene scenery of a man, reading, accompanied by his faithful city bike",
  },

  x11_1: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x11_1.jpg",
    // ph: "11_1",
    title: "Capturing..",
    meta: "Tokyo Station, Tokyo · 2024",
    ar: 1.5,
    note: "The moment when capturing the scene of Tokyo Station",
  },
  x11_2: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall-x11_2.jpg",
    // ph: "11_2",
    title: "Capturing..",
    meta: "Tokyo Station, Tokyo · 2024",
    ar: 1.5,
    note: "The moment when capturing the scene of Tokyo Station",
  },
  x11_3: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall_x11_3.jpg",
    // ph: "11_3",
    title: "Capturing..",
    meta: "Tokyo Station, Tokyo · 2024",
    ar: 1.5,
    note: "The moment when capturing the scene of Tokyo Station",
  },
  x11_4: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/hall_x11_4.jpg",
    // ph: "11_4",
    title: "Capturing..",
    meta: "Tokyo Station, Tokyo · 2024",
    ar: 1.5,
    note: "The moment when capturing the scene of Tokyo Station",
  },
  
  x6: {
    // ph: "PHOTO 09 · 2:3",
    src: 'https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/east_x6.jpg',
    title: "The Airport",
    meta: "I Gusti Ngurah Rai Airport, Badung",
    ar: 2 / 3,
    note: "the in the middle plane between a gapura",
  },
  x4: {
    // ph: "PHOTO 07 · 3:2",
    src: 'https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/east_x4.jpg',
    title: "The Station Slow Shutter",
    meta: "-",
    ar: 1.5,
    note: "the very",
  },
  x5: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/east_x5.jpg",
    title: "Get on the Angkot",
    meta: "Lebak Bulus MRT Station, South Jakarta",
    ar: 1.5,
    note: "a regular angkot near Lebak Bulus MRT Station",
  },
  e1: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/east_e1.jpg",
    // ph: "e_1",
    title: "Capturing..",
    meta: "Tokyo Station, Tokyo · 2024",
    ar: 1.5,
    note: "The moment when capturing the scene of Tokyo Station",
  },
  e2: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/east_e2.jpg",
    // ph: "e_2",
    title: "Capturing..",
    meta: "Tokyo Station, Tokyo · 2024",
    ar: 1.5,
    note: "The moment when capturing the scene of Tokyo Station",
  },
  e3: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/east_e3.jpg",
    // ph: "e_3",
    title: "Capturing..",
    meta: "Tokyo Station, Tokyo · 2024",
    ar: 1,
    note: "The moment when capturing the scene of Tokyo Station",
  },
  e4: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/east_e4.jpg",
    // ph: "e_4",
    title: "Capturing..",
    meta: "Tokyo Station, Tokyo · 2024",
    ar: 1,
    note: "The moment when capturing the scene of Tokyo Station",
  },
  e5: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/east_e5.jpg",
    // ph: "e_5",
    title: "Capturing..",
    meta: "Tokyo Station, Tokyo · 2024",
    ar: 2 / 3,
    note: "The moment when capturing the scene of Tokyo Station",
  },
  e6: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/east_e6.jpg",
    // ph: "e_6",
    title: "Capturing..",
    meta: "Tokyo Station, Tokyo · 2024",
    ar: 1.5,
    note: "The moment when capturing the scene of Tokyo Station",
  },
  e7: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/east_e7.jpg",
    // ph: "e_7",
    title: "Capturing..",
    meta: "Tokyo Station, Tokyo · 2024",
    ar: 2/3,
    note: "The moment when capturing the scene of Tokyo Station",
  },

  n1: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/north_n1.jpg",
    // ph: "n_1",
    title: "Capturing..",
    meta: "Tokyo Station, Tokyo · 2024",
    ar: 1.5,
    note: "The moment when capturing the scene of Tokyo Station",
  },
  n2: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/north_n2.jpg",
    // ph: "n_2",
    title: "Capturing..",
    meta: "Tokyo Station, Tokyo · 2024",
    ar: 1.5,
    note: "The moment when capturing the scene of Tokyo Station",
  },
  n3: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/north_n3.jpg",
    // ph: "n_3",
    title: "Capturing..",
    meta: "Tokyo Station, Tokyo · 2024",
    ar: 1.5,
    note: "The moment when capturing the scene of Tokyo Station",
  },
  n4: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/north_n4.jpg",
    // ph: "n_4",
    title: "Capturing..",
    meta: "Tokyo Station, Tokyo · 2024",
    ar: 2/3,
    note: "The moment when capturing the scene of Tokyo Station",
  },
  n5: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/north_n5.jpg",
    // ph: "n_5",
    title: "Capturing..",
    meta: "Tokyo Station, Tokyo · 2024",
    ar: 2/3,
    note: "The moment when capturing the scene of Tokyo Station",
  },
  n6: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/north_n6.JPG",
    // ph: "n_6",
    title: "Capturing..",
    meta: "Tokyo Station, Tokyo · 2024",
    ar: 1.5,
    note: "The moment when capturing the scene of Tokyo Station",
  },
  n7: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/north_n7.jpg",
    // ph: "n_7",
    title: "Capturing..",
    meta: "Tokyo Station, Tokyo · 2024",
    ar: 2/3,
    note: "The moment when capturing the scene of Tokyo Station",
  },
  n8: {
    src: "https://nos.wjv-1.neo.id/baec-portfolio-bucket/assets/north_n8.JPG",
    // ph: "n_8",
    title: "Capturing..",
    meta: "Tokyo Station, Tokyo · 2024",
    ar: 2/3,
    note: "The moment when capturing the scene of Tokyo Station",
  },
};
